services:
  producer:
    container_name: producer
    depends_on:
      pgdb:
        condition: service_healthy
      #- brocker
    build:
      dockerfile: ./API/Dockerfile
      context: ./NotificationKeeper
    ports:
      - 8080:8080
    

  # consumer:
  #   build: ./EmailNotificator/View/Dockerfile
  #   container_name: consumer
  #   ports:
  #     - 50:50

  logDatabase:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: ThereFox
      DOCKER_INFLUXDB_INIT_PASSWORD: testPassword123
      DOCKER_INFLUXDB_INIT_ORG: ThereFoxOrganisation
      DOCKER_INFLUXDB_INIT_BUCKET: TestBucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: TestToken
    ports:
      - 8051:8086

  zookeeper: 
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: ubuntu/kafka:latest
    environment:
      - TZ=UTC
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    depends_on:
      - zookeeper
      - producer
    ports:
      - 9092:9092

  pgdb:
    image: postgres:latest
    container_name: notificationDB
    environment:
      - POSTGRES_DB=Notifications123
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_USER=dbAccesor
    ports:
      - 5432:5432
    volumes:
      - databaseVolume:/mnt/c/Users/Elcu/Videos/Data/Database
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 20s

  adminDB:
    profiles:
      - WithUIDebug
    image: elestio/pgadmin:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: test@test.com
        PGADMIN_DEFAULT_PASSWORD: test123
        PGADMIN_LISTEN_PORT: 7070
    ports:
      - 7070:7070

  conduktor-console:
    profiles:
      - WithUIDebug
    image: conduktor/conduktor-console:1.25.1
    #depends_on:
    #  - brocker
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: "./console-config.yaml"
        target: /opt/conduktor/console-config.yaml
        read_only: true
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/console-config.yaml

  conduktor-monitoring:
    profiles:
      - WithUIDebug
    image: conduktor/conduktor-console-cortex:1.25.1
    ports:
      - 8083:8080
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8082"

volumes:
  brockerMessages:
    driver: local
  databaseVolume:
    driver: local